### ISSUE TITLE
avahi discovery times out

### ISSUE THREAD

**Issue by markushuber** [usableprivacy/upribox#104]
`avahi-browse` fails to resolve the upribox services and times out. This bug also means the customizer is unable to detect local upriboxes.

![selection_012](https://user-images.githubusercontent.com/790934/32715403-8227e5e4-c852-11e7-8204-455f0fc38551.png)

This issue can be related to our `avahi` config or recent changes in `iptables`.

**Comment by tobiasdam** [comment]
During system startup, avahi thinks for some reason that wlan0 is a relevant interface, but removes the interface after some time. If the interface is removed before the avahi server startup is finished, the upribox service is brought up successfully, otherwise bringing up the sevice never finishes.

After this config change, avahi only listens on eth0, name resolution of upribox.local on other interfaces (wlan0) is handled by dnsmasq.
